discord-webhook-url: ''

# HTTP User-Agent field when submitting data to Discord
http-user-agent: 'DiscordLogger'

# The prefix to prepend to the log message when submitting it to web hook
message-prefix: ''

# Prefixes to ignore
ignored-log-prefixes:
  - '    at java.'
  - '    at sun.'

# If to prefix the log level
prefix-log-level: true

log-keywords:
  - ''

# The type of log levels to submit for Discord
log-levels:
  - 'SEVERE'
  - 'WARNING'