discord-webhook-url: ''

# HTTP User-Agent field when submitting data to Discord
http-user-agent: 'DiscordLogger'

# The prefix to prepend to the log message when submitting it to web hook
message-prefix: ''

# Prefixes to ignore. Whitespace is automatically trimmed (output of string.trim())
ignored-log-prefixes:
  - 'at java.'
  - 'at sun.'

ignored-log-words:
  - 'UpstreamBridge'
  - 'InitialHandler'

# If to prefix the log level
prefix-log-level: true

# If to remove ip addresses before submitting data to Discord
remove-ips: true

# If to remove urls before submitting data to Discord
remove-urls: true

# Keywords are split by a space
log-keywords:
  - ''

# The type of log levels to submit for Discord
log-levels:
  - 'SEVERE'