discord-webhook-url: ''

# HTTP User-Agent field when submitting data to Discord
http-user-agent: 'DiscordLogger'

# The prefix to prepend to the log message when submitting it to web hook
message-prefix: '[DiscordLogger] '

# Log the message if it contains any one of the keywords
# All keywords are case-sensitive
log-keywords:
  - '[SEVERE]'
  - '[WARNING]'